<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html [
	
	<!ELEMENT html (head, body)>
	<!ELEMENT head (charset, title, link)>
	<!ELEMENT link (relation, href)>
	<!ELEMENT body (wrapper)>

	<!ELEMENT wrapper (header, navigation, banner, main, footer)>
	<!ELEMENT header (logo-img, href, images)>
	<!ELEMENT images (png)>

	<!ELEMENT navigation (nav-items)>
	<!ELEMENT nav-items (u-list)>
	<!ELEMENT u-list (active, item)>
	<!ELEMENT active (item)>

	<!ELEMENT banner (img)>
	<!ELEMENT img (images)>
	<!ELEMENT images (jpg)>

	<!ELEMENT main (l-sidebar, content, r-sidebar)>
	<!ELEMENT l-sidebar (heading, u-list)>
	<!ELEMENT u-list (list)>

	<!ELEMENT content (heading, description, description-2, img, button)>
	<!ELEMENT heading (name)>

	<!ELEMENT description (echo)>
	<!ELEMENT img (images)>
	<!ELEMENT images (png)>
	<!ELEMENT heading (href)>
	<!ELEMENT href (name)>

	<!ELEMENT description-2 (echo)>
	<!ELEMENT button (href)>
	<!ELEMENT href (name)>

	<!ELEMENT r-sidebar (img-list)>
	<!ELEMENT img-list (heading, list)>
	<!ELEMENT list (href)>
	<!ELEMENT images (jpg)>

	<!ELEMENT footer (paragraph, icons)>
	<!ELEMENT icons (u-list)>
	<!ELEMENT u-list (href)>
	<!ELEMENT href (images)>
	<!ELEMENT images (icons)>
	<!ELEMENT icons (png)>

	<!ELEMENT head (#PCDATA)>
	<!ELEMENT body (#PCDATA)>
	<!ELEMENT charset (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT link (#PCDATA)>
	<!ELEMENT relation (#PCDATA)>
	<!ELEMENT href (#PCDATA)>
	<!ELEMENT wrapper (#PCDATA)>
	<!ELEMENT header (#PCDATA)>
	<!ELEMENT navigation (#PCDATA)>
	<!ELEMENT banner (#PCDATA)>
	<!ELEMENT main (#PCDATA)>
	<!ELEMENT footer (#PCDATA)>
	<!ELEMENT logo-img (#PCDATA)>
	<!ELEMENT images (#PCDATA)>
	<!ELEMENT png (#PCDATA)>
	<!ELEMENT nav-items (#PCDATA)>
	<!ELEMENT u-list (#PCDATA)>
	<!ELEMENT active (#PCDATA)>
	<!ELEMENT item (#PCDATA)>
	<!ELEMENT img (#PCDATA)>
	<!ELEMENT jpg (#PCDATA)>
	<!ELEMENT l-sidebar (#PCDATA)>
	<!ELEMENT content (#PCDATA)>
	<!ELEMENT r-sidebar (#PCDATA)>
	<!ELEMENT heading (#PCDATA)>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT description-2 (#PCDATA)>
	<!ELEMENT button (#PCDATA)>
	<!ELEMENT echo (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT img-list (#PCDATA)>
	<!ELEMENT paragraph (#PCDATA)>
	<!ELEMENT icons (#PCDATA)>

	<!ATTLIST href link CDATA #REQUIRED>
	<!ATTLIST images title CDATA #REQUIRED>
	<!ATTLIST item link CDATA #REQUIRED>
	<!ATTLIST heading id CDATA #REQUIRED>
	<!ATTLIST img pic CDATA #REQUIRED>
	<!ATTLIST paragraph style CDATA #REQUIRED>
	<!ATTLIST href h-link CDATA #REQUIRED>

]>
<html>
	<head>
		<charset>UTF-8</charset>
		<title>Hapag-Filipino Cuisine and Recipes</title>
		<link>
			<relation>stylesheet</relation>
			<href>css/style.css</href>
		</link>
	</head>

	<body>
		<wrapper>
			<header>
				<logo-img>
					<href link="index.php">
						<images title="logo">
							<png>logo</png>
						</images>
					</href>
				</logo-img>
			</header>
			<navigation>
				<nav-items>
					<u-list>
						<active>
							<item link="index.php">HOME</item>
						</active>
						<item link="recipes.php">RECIPES</item>
						<item link="about.php">ABOUT</item>
					</u-list>
				</nav-items>
			</navigation>
			<banner>
				<img>
					<images title="Pork Adobo">
						<jpg>bannerhome</jpg>
					</images>
				</img>
			</banner>
			<main>
				<l-sidebar>
					<heading id="2">Content</heading>
					<u-list>
						<list>Home</list>
						<list>Hapag Recipes</list>
					</u-list>
				</l-sidebar>

				<content>
					<heading id="1">Home</heading>
					<description>
						<echo>
							Mabuhay! Feel free to browse to our Hapag Filipino dishes. There are mainly three categories to our easy. Filipino recipes that you can choose from; these Filipino recipes are categorized from Breakfast to Dinner and as well as some Filipino desserts that you will surely love. The reason for showcasing only the Filipino cuisine is that we want to show to the people who havenâ€™t tried Filipino food or dishes that Filipino classic food is delicious and can be love by many, even to those people around the world. We provide step by step instructions which will make learning Filipino dishes easy and guide people to cook more confidently for creating simple but delightful food.
						</echo>
					</description>
					<heading id="1">
						<name>Hapag Recipes</name>
					</heading>
					<img pic="1">
						<images title="Tortang Talong">
							<png>torta</png>
						</images>
					</img>
					<heading id="3">
						<href link="recipe3.php">
							<name title="Read more">
								Tortang Talong
							</name>
						</href>
					</heading>
					<img pic="2">
						<images title="Bicol Express">
							<png>bicolexpress</png>
						</images>
					</img>
					<heading id="3">
						<href link="recipe14.php">
							<name title="Read more">
								Bicol Express
							</name>
						</href>
					</heading>
					<img pic="3">
						<images title="Tinolang Manok">
							<jpg>tinola</jpg>
						</images>
					</img>
					<heading id="3">
						<href link="recipe11.php">
							<name title="Read more">
								Tinolang Manok
							</name>
						</href>
					</heading>
					<img pic="4">
						<images title="Turon">
							<jpg>turon</jpg>
						</images>
					</img>
					<heading id="3" >
						<href link="recipe18.php">
							<name title="Read more">
								Turon
							</name>
						</href>
					</heading>
					<description-2>
						<echo>
							This are just the few Filino recipes that you will love to cook and eat. If you are interested to explore more recipes then go to our navigation and click recipes for more.
						</echo>
					</description-2>
					<button>
						<href link="recipes.php">
							<name>MORE RECIPES</name>
						</href>
					</button>										
				</content>

				<r-sidebar>
					<img-list>
						<heading id="5">Latest Recipes</heading>
						<list>
							<href link="recipe1.php">
								<images>
									<jpg>tapsilog</jpg>
								</images>
							</href>
						</list>
						<heading id="4">Tapsilog</heading>
						<list>
							<href link="recipe16.php">
								<images>
									<jpg>halohalo</jpg>
								</images>
							</href>
						</list>
						<heading id="4">Halo-Halo</heading>
						<list>
							<href link="recipe7.php">
								<images>
									<jpg>sinigang</jpg>
								</images>
							</href>
						</list>
						<heading id="4">Sinigang</heading>
						<list>
							<href link="recipe5.php">
								<images>
									<jpg>bibingka</jpg>
								</images>
							</href>
						</list>
						<heading id="4">Bibingka</heading>
						<list>
							<href link="recipe13.php">
								<images>
									<jpg>chopsuey</jpg>
								</images>
							</href>
						</list>
						<heading id="4">Chop Suey</heading>
					</img-list>
				</r-sidebar>
			</main>
			<footer>
				<paragraph style="bold">
					2022 Hapag: Filipino Cuisine and Recipe Gerson O. Pantoja Masiga, Gasan, Marinduque - Philippines Tel No. 0923 1343 342. All rights reserved.
				</paragraph>
				<icons>
					<u-list>
						<href h-link="https://web.facebook.com/login/?_rdc=1_rdr">
							<images>
								<icons>
									<png>facebook</png>
								</icons>
							</images>
						</href>
						<href h-link="https://www.instagram.com/?hl=en">
							<images>
								<icons>
									<png>instagram</png>
								</icons>
							</images>
						</href>
						<href h-link="https://www.pinterest.ph/">
							<images>
								<icons>
									<png>pinterest</png>
								</icons>
							</images>
						</href>
						<href h-link="https://www.youtube.com/">
							<images>
								<icons>
									<png>youtube</png>
								</icons>
							</images>
						</href>
					</u-list>
				</icons>
			</footer>
		</wrapper>
	</body>
</html>